server:
  port: 9090
spring:
  application:
    name: SALEX-API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: ROUTE-A
          uri: http://localhost:8081
          predicates:
            - Path=/v1/**
        - id: ROUTE-B
          uri: http://localhost:8082
          predicates:
            - Path=/v1/**
        - id: ROUTE-C
          uri: http://localhost:8083
          predicates:
            - Path=/v1/**