server:
  port: 9090
  ssl:
    key-store: classpath:cert-chain.p12
    key-store-password: root@2580
    keyStoreType: PKCS12
    #keyAlias: tomcat
spring:
  application:
    name: SALEX-API-GATEWAY-SERVICE
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ROUTE-A
          uri: http://localhost:8081
          predicates:
            - Path=/v1/**
          filters:
            - name: CacheRequestBody
        - id: ROUTE-B
          uri: http://localhost:8082
          predicates:
            - Path=/v1/**
          filters:
            - name: CacheRequestBody
        - id: ROUTE-C
          uri: http://localhost:8083
          predicates:
            - Path=/v1/**
          filters:
            - name: CacheRequestBody

        - id: ROUTE-D
          uri: http://localhost:8081
          predicates:
            - Path=/file/**
        - id: ROUTE-E
          uri: http://localhost:8082
          predicates:
            - Path=/file/**
        - id: ROUTE-F
          uri: http://localhost:8083
          predicates:
            - Path=/file/**


        - id: ROUTE-RECRUTINOW-A
          uri: http://localhost:8091
          predicates:
            - Path=/rn/**
        - id: ROUTE-RECRUTINOW-B
          uri: http://localhost:8092
          predicates:
            - Path=/rn/**
        - id: ROUTE-RECRUTINOW-C
          uri: http://localhost:8093
          predicates:
            - Path=/rn/**